// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdc6n9JBxYbpNqHrvkguYOfh4nT6BQo2I',
    appId: '1:924674236713:web:1067df2da421ab143f9738',
    messagingSenderId: '924674236713',
    projectId: 'task3-161ae',
    authDomain: 'task3-161ae.firebaseapp.com',
    storageBucket: 'task3-161ae.firebasestorage.app',
    measurementId: 'G-BGM1MN4TPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz9kjt5irBr545CaylJK5IllDM5J1rHhU',
    appId: '1:924674236713:android:dad938d4fbf46aa93f9738',
    messagingSenderId: '924674236713',
    projectId: 'task3-161ae',
    storageBucket: 'task3-161ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfx6qyIqQ3wKrhd2XJmCuWJUpOkSUOalw',
    appId: '1:924674236713:ios:30a5806a78e726de3f9738',
    messagingSenderId: '924674236713',
    projectId: 'task3-161ae',
    storageBucket: 'task3-161ae.firebasestorage.app',
    iosBundleId: 'com.example.task3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfx6qyIqQ3wKrhd2XJmCuWJUpOkSUOalw',
    appId: '1:924674236713:ios:30a5806a78e726de3f9738',
    messagingSenderId: '924674236713',
    projectId: 'task3-161ae',
    storageBucket: 'task3-161ae.firebasestorage.app',
    iosBundleId: 'com.example.task3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdc6n9JBxYbpNqHrvkguYOfh4nT6BQo2I',
    appId: '1:924674236713:web:161e73cb4e3c80bd3f9738',
    messagingSenderId: '924674236713',
    projectId: 'task3-161ae',
    authDomain: 'task3-161ae.firebaseapp.com',
    storageBucket: 'task3-161ae.firebasestorage.app',
    measurementId: 'G-MX7T401VFE',
  );
}
